#!/bin/bash

# Copyright (c) 2007 Red Hat, Inc.
#
# This file is part of the Qpid async store library msgstore.so.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA
#
# The GNU Lesser General Public License is available in the file COPYING.


JRNL_BLK_SIZE=512 # Block size in bytes
JRNL_PAGE_SIZE=256 # Journal page size in blocks
JRNL_FILE_SIZE=12  # Journal file size in pages
let END_OFFSET=${JRNL_BLK_SIZE}*${JRNL_PAGE_SIZE}*${JRNL_FILE_SIZE}
for f in jdata/test.*.jdat; do
    echo $f
    hexdump -C -n 1024 $f
    hexdump -C -s ${END_OFFSET} $f
    echo "============"
done
