#!/bin/bash

# Copyright (c) 2008 Red Hat, Inc.
#
# This file is part of the Qpid async store library msgstore.so.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
# USA
#
# The GNU Lesser General Public License is available in the file COPYING.

# Stop the broker, check for errors.
# 
if test -f qpidd.port; then
    export QPID_PORT=`cat qpidd.port`
    QPIDD=$QPID_BLD/src/qpidd
    rm -f qpidd.port

    $QPIDD --quit || ERROR=$?

    # Check qpidd.log.
    grep -a 'warning\|error\|critical' qpidd.log && {
        echo "WARNING: Suspicious broker log entries in qpidd.log, above."
    }

    # Check valgrind log.
    if test -n "$VALGRIND"; then
        source `dirname $0`/vg_check $VG_LOG*
        vg_check qpidd.vglog*
    fi

    exit $ERROR
else
    echo "No qpidd.port file found - cannot stop broker."
    exit 1;
fi
